Add missing commands (#1)
* feat: try to implement all commands

* ci: use matrix for testing

* ci: set dokku version correctly

* fix(ci): set correct env var

* feat: link to apps correctly

* fix: increase wait time

* feat: create instances

* fix: do not redirect outputs

* refactor: extract wait time to config var

* feat: use cli to create instance

* feat(link): add correct options needed

* fix(link): use correct hostname

* feat(example): add example app

* docs: add important notes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,25 +1,39 @@
 #!/usr/bin/env bash
-set -eo pipefail
-
-[[ $DOKKU_TRACE ]] && set -x
-
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
 source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common-functions"
+set -eo pipefail
+[[ $DOKKU_TRACE ]] && set -x
 
 plugin-install() {
-    pull_docker_images
+  pull-docker-image() {
+    declare IMAGE="$1"
+    if [[ "$PLUGIN_DISABLE_PULL" == "true" ]]; then
+      echo " !     ${PLUGIN_DISABLE_PULL_VARIABLE} environment variable detected. Not running pull command." 1>&2
+      echo " !        docker pull ${IMAGE}" 1>&2
+      return
+    fi
+    if [[ "$(docker images -q "${IMAGE}" 2>/dev/null)" == "" ]]; then
+      docker pull "${IMAGE}"
+    fi
+  }
 
-    mkdir -p "$PLUGIN_DATA_ROOT" || echo "Failed to create $PLUGIN_SERVICE data directory"
-    chown "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "$PLUGIN_DATA_ROOT"
+  pull-docker-image "${PLUGIN_IMAGE}:${PLUGIN_IMAGE_VERSION}"
+  pull-docker-image "$PLUGIN_BUSYBOX_IMAGE"
+  pull-docker-image "$PLUGIN_AMBASSADOR_IMAGE"
+  pull-docker-image "$PLUGIN_S3BACKUP_IMAGE"
+  pull-docker-image "$PLUGIN_WAIT_IMAGE"
 
-    mkdir -p "$PLUGIN_CONFIG_ROOT" || echo "Failed to create $PLUGIN_SERVICE config directory"
-    chown "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "$PLUGIN_CONFIG_ROOT"
+  mkdir -p "$PLUGIN_DATA_ROOT" || echo "Failed to create $PLUGIN_SERVICE data directory"
+  chown "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "$PLUGIN_DATA_ROOT"
 
-    rm -f "/etc/sudoers.d/dokku-${PLUGIN_COMMAND_PREFIX}*"
-    _SUDOERS_FILE="/etc/sudoers.d/dokku-${PLUGIN_COMMAND_PREFIX}"
+  mkdir -p "$PLUGIN_CONFIG_ROOT" || echo "Failed to create $PLUGIN_SERVICE config directory"
+  chown "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "$PLUGIN_CONFIG_ROOT"
 
-    touch "$_SUDOERS_FILE"
-    cat >"$_SUDOERS_FILE" <<EOL
+  rm -f "/etc/sudoers.d/dokku-${PLUGIN_COMMAND_PREFIX}*"
+  _SUDOERS_FILE="/etc/sudoers.d/dokku-${PLUGIN_COMMAND_PREFIX}"
+
+  touch "$_SUDOERS_FILE"
+  cat >"$_SUDOERS_FILE" <<EOL
 %dokku ALL=(ALL) NOPASSWD:/bin/rm -f /etc/cron.d/dokku-${PLUGIN_COMMAND_PREFIX}-*
 %dokku ALL=(ALL) NOPASSWD:/bin/chown root\:root /etc/cron.d/dokku-${PLUGIN_COMMAND_PREFIX}-*
 %dokku ALL=(ALL) NOPASSWD:/bin/chmod 644 /etc/cron.d/dokku-${PLUGIN_COMMAND_PREFIX}-*
@@ -28,7 +42,26 @@ plugin-install() {
 %dokku ALL=(ALL) NOPASSWD:/bin/chgrp 8983 $PLUGIN_DATA_ROOT/*
 EOL
 
-    chmod 0440 "$_SUDOERS_FILE"
+  chmod 0440 "$_SUDOERS_FILE"
+
+  for SERVICE in $(fn-services-list false); do
+    local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
+
+    if [[ ! -f "$SERVICE_ROOT/IMAGE" ]] || [[ ! -f "$SERVICE_ROOT/IMAGE_VERSION" ]]; then
+      local image="$(service_version "$SERVICE")"
+      if [[ "$image" == *":"* ]]; then
+        echo "${image%:*}" >"$SERVICE_ROOT/IMAGE"
+        echo "${image##*:}" >"$SERVICE_ROOT/IMAGE_VERSION"
+      fi
+    fi
+
+    chown "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "$SERVICE_ROOT/IMAGE" "$SERVICE_ROOT/IMAGE_VERSION"
+
+    if [[ -f "$SERVICE_ROOT/${PLUGIN_VARIABLE}_CONFIG_OPTIONS" ]]; then
+      mv "$SERVICE_ROOT/${PLUGIN_VARIABLE}_CONFIG_OPTIONS" "$SERVICE_ROOT/CONFIG_OPTIONS"
+      chown "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "$SERVICE_ROOT/CONFIG_OPTIONS"
+    fi
+  done
 }
 
 plugin-install "$@"
